[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"
authors = ["Dima Lazarev <dmitry.lazarev@gmail.com>"]

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
aoc-parse = "0.2.18"
num = "0.4"